version: '3'

services:

  app:
    build:
      context: .
      dockerfile: ./training-system/Dockerfile
    privileged: true
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/word_train
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - nw
    depends_on:
      - postgres

  email:
    build:
      context: .
      dockerfile: ./email-notification/Dockerfile
    ports:
      - "9090:9090"
    environment:
      - SERVER_EMAIL=admin@example.com
      - EMAIL_SERVER_USER=admin
      - EMAIL_SERVER_PASSWORD=password
      - SPRING_RABBITMQ_ADDRESSES=amqp://user:password@rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - nw

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    depends_on:
      - app
  postgres:
    image: "postgres"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=word_train
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - nw
networks:
  nw: